name: Check Build And Assemble

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: gradle build -q
      - name: Copy APK
        uses: actions/upload-artifact@v2
        with:
          name: AD2-prod-debug.apk
          path: app/build/outputs/apk/prod/debug/app-prod-debug.apk