name: Check Build And Assemble

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Use Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties','**/libs.versions.toml') }}
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Generate local.properties file
        env:
          IS_CI: ${{ secrets.IS_CI }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        shell: cmd
        run: |
          echo isCI=%IS_CI% > local.properties
          echo KEY_ALIAS=%KEY_ALIAS% >> local.properties
          echo KEY_PASSWORD=%KEY_PASSWORD% >> local.properties
          echo STORE_PASSWORD=%STORE_PASSWORD% >> local.properties
          echo SIGNING_FILE=key.jks >> local.properties
      - name: Build with Gradle
        run: gradle build --no-daemon --stacktrace
      - name: Copy APK
        uses: actions/upload-artifact@v3
        with:
          name: AD2-prod-debug.apk
          path: app/build/outputs/apk/debug/*.apk
  measure:
    if: false
    runs-on: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Generate local.properties file
        env:
          IS_CI: ${{ secrets.IS_CI }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        shell: cmd
        run: |
          echo isCI=%IS_CI% > local.properties
          echo KEY_ALIAS=%KEY_ALIAS% >> local.properties
          echo KEY_PASSWORD=%KEY_PASSWORD% >> local.properties
          echo STORE_PASSWORD=%STORE_PASSWORD% >> local.properties
          echo SIGNING_FILE=key.jks >> local.properties
      - name: MeasureBuild
        run: gradle measureBuild --no-daemon
      - name: Copy Measurment
        shell: cmd
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add gradle/profiler
          git commit -m "update gradle-profiler files"
          git push