name: Check Build And Assemble

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx2g

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: check Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'oracle'
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}

      - name: Generate local.properties file
        shell: bash
        env:
          IS_CI: ${{ secrets.IS_CI }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: |
          echo isCI="$IS_CI" > local.properties
          echo KEY_ALIAS="$KEY_ALIAS" >> local.properties
          echo KEY_PASSWORD="$KEY_PASSWORD" >> local.properties
          echo STORE_PASSWORD="$STORE_PASSWORD" >> local.properties
          echo SIGNING_FILE=key.jks >> local.properties
          cat local.properties

      - name: Build with Gradle
        run: ./gradlew build --no-daemon --no-configuration-cache

      - name: Copy APK
        uses: actions/upload-artifact@v4
        with:
          name: AD2-prod-debug.apk
          path: app/build/outputs/apk/debug/*.apk

  measure:
    if: false
    runs-on: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: gradle
      - name: Generate local.properties file
        shell: cmd
        run: |
          echo isCI=%IS_CI% > local.properties
          echo KEY_ALIAS=%KEY_ALIAS% >> local.properties
          echo KEY_PASSWORD=%KEY_PASSWORD% >> local.properties
          echo STORE_PASSWORD=%STORE_PASSWORD% >> local.properties
          echo SIGNING_FILE=key.jks >> local.properties
      - name: MeasureBuild
        run: gradle measureBuild --no-daemon -q
      - name: Copy Measurment
        shell: cmd
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add gradle/profiler
          git commit -m "update gradle-profiler files"
          git push
