name: Generate File

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Use Cache
        uses: actions/cache@v2
        with:
         path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
         key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Generate local.properties file
        env:
          IS_CI: ${{ secrets.IS_CI }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        shell: cmd
        run: |
          echo isCI=%IS_CI% > generated.txt
          echo KEY_ALIAS=%KEY_ALIAS% >> generated.txt
          echo KEY_PASSWORD=%KEY_PASSWORD% >> generated.txt
          echo STORE_PASSWORD=%STORE_PASSWORD% >> generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add generated.txt
          git commit -m "generate file"
          git push
              
      
