name: Generate File

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: do commit
        run: |
           date > generated.txt
           git config user.name github-actions
           git config user.email github-actions@github.com
           git add generated.txt
           git commit -m "generate file"
           git push
              
      
