name: unit_tests

on:
  push:
    branches: 
      - 'master1111111'
  pull_request:
    branches:
      - 'master1111111'

jobs:
 Unit-test:
  name: Run unit tests
  runs-on: ubuntu-20.04

  steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with: {java-version: 1.8}
    - name: Run unit tests
      run: ./gradlew test
