name: Update Gradle Wrapper
on:
  schedule:
    - cron: "0 0 * * *" # GitHub runs the workflow every day at midnight
jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Change wrapper permissions
          run: chmod +x ./gradlew

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          paths: gradle/wrapper/**