name: Update Gradle Wrapper
on:
  schedule:
    - cron: "0 0 * * *" # GitHub runs the workflow every day at midnight
jobs:
  update-gradle-wrapper:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
